service: cmcs-eregs-site
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  iam:
    role: LambdaFunctionRole
  logs:
    restApi:
      level: INFO
      roleManagedExternally: true
  lambdaHashingVersion: '20201221'
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
      - 'application/pdf'
  environment:
    DB_NAME: ${self:custom.settings.DB_NAME}
    DB_USER: ${self:custom.settings.USERNAME}
    DB_PASSWORD: ${ssm:/eregulations/db/password}
    DB_HOST: ${ssm:/eregulations/db/host}
    DB_PORT: ${ssm:/eregulations/db/port}
    GA_ID: ""
    HTTP_AUTH_USER: "user"
    HTTP_AUTH_PASSWORD: "password"
    DJANGO_USERNAME: "user"
    DJANGO_PASSWORD: "password"
    DJANGO_ADMIN_USERNAME: "user"
    DJANGO_ADMIN_PASSWORD: "password"
    DJANGO_SETTINGS_MODULE: "cmcs_regulations.settings.test_settings"
    ALLOWED_HOST: '.amazonaws.com'
    STAGE_ENV: ${self:custom.stage}
    STATIC_URL: "/"
    BASE_URL: "/"
    CUSTOM_URL: "/"
    SURVEY_URL: "/"
    SIGNUP_URL: "/"
    SEARCHGOV_KEY: "/"
    SEARCHGOV_SITE_NAME: "/"
    OIDC_RP_CLIENT_ID:  "/"
    OIDC_RP_CLIENT_SECRET: "/"
    OIDC_OP_AUTHORIZATION_ENDPOINT: "/"
    OIDC_OP_TOKEN_ENDPOINT: "/"
    OIDC_OP_JWKS_ENDPOINT: "/"
    OIDC_OP_USER_ENDPOINT: "/"
    OIDC_END_EUA_SESSION: "/"
    BASIC_SEARCH_FILTER: "0.05"
    QUOTED_SEARCH_FILTER: "0.05"
    EUA_FEATUREFLAG: false
    DEPLOY_NUMBER: ${env:RUN_ID}
    AWS_STORAGE_BUCKET_NAME: eregulations-file-repo-eregs-${self:custom.stage}
    TEXT_EXTRACTOR_ARN: arn:aws:iam::227463533165:role/MyARN
  tracing:
    apiGateway: true
  vpc:
    securityGroupIds:
      - !Ref ServerlessSecurityGroup
    subnetIds:
      - ${ssm:/account_vars/vpc/subnets/private/a/id}
      - ${ssm:/account_vars/vpc/subnets/private/b/id}
  deploymentBucket:
    blockPublicAccess: true
package:
  individually: false
  exclude:
    - node_modules/**
    - nginx/**

custom:
  stage: ${opt:stage, self:provider.stage}
  wsgi:
    app: handler.application
    packRequirements: false
  settings:
    static_url: ${cf:cmcs-eregs-static-assets-${self:custom.stage}.StaticURL}/
    DB_NAME: eregs
    USERNAME: eregsuser
    ALLOWED_HOST: '.amazonaws.com'
    text_extractor_arn: "arn:aws:iam::227463533165:role/MyARN"
  cloudfrontInvalidate:
    - distributionId: ${cf:cmcs-eregs-static-assets-${self:custom.stage}.CloudFrontDistributionId}
      items:
        - "/*"
  associateWaf:
    name: APIGateway-eregs-allow-usa-plus-territories-${self:custom.stage}
    version: V2

functions: ${file(serverless_functions/${self:custom.stage}_functions.yml)}


resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: eregulations-file-repo-eregs-${self:custom.stage}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - HEAD
              MaxAge: 3000
    WAFRegionalWebACL: ${file(aws_resources/waf.yml):WAFRegionalWebACL}
    LambdaFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: ${ssm:/account_vars/iam/path}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        # note that these rights are needed if you want your function to be able to communicate with resources within your vpc
        #PermissionsBoundary:
        #  Fn::Join:
        #    - ''
        #    - - 'arn:aws:iam::'
        #      - Ref: AWS::AccountId
        #      - ':policy'
         #     - ${ssm:/account_vars/iam/permissions_boundary_policy}
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: StorageBucketPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Deny
                  Action: "*"
                  Condition:
                    Bool:
                      "aws:SecureTransport": false
                  Resource:
                    - Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - "Ref" : "ServerlessDeploymentBucket"
                    - "arn:aws:s3:::eregulations-file-repo-eregs-${self:custom.stage}/*"
          - PolicyName: LambdaPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                -  Effect: "Allow"
                   Action:
                     - "s3:PutObject"
                     - "s3:GetObject"
                     - "s3:DeleteObject"
                     - "ec2:DescribeNetworkInterfaces"
                     - "ec2:CreateNetworkInterface"
                     - "ec2:DeleteNetworkInterface"
                     - "ec2:DescribeInstances"
                     - "ec2:AttachNetworkInterface"
                   Resource:
                     - Fn::Join:
                       - ""
                       - - "arn:aws:s3:::"
                         - "Ref" : "ServerlessDeploymentBucket"
                     - "arn:aws:s3:::eregulations-file-repo-eregs-${self:custom.stage}/*"
                -  Effect: "Allow"
                   Action:
                     - "lambda:InvokeFunction"
                   Resource:
                     - "${self:custom.settings.text_extractor_arn}"     
    ServerlessSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SecurityGroup for Serverless Functions
        VpcId: ${ssm:/account_vars/vpc/id}
        Tags:
          - Key: "Name"
            Value: "ServerlessSecurityGroup"

    DBSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SecurityGroup for Database
        VpcId: ${ssm:/account_vars/vpc/id}
        Tags:
          - Key: "Name"
            Value: "DBSecurityGroup"

    DBSecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        GroupId: !Ref 'DBSecurityGroup'
        IpProtocol: tcp
        FromPort: ${ssm:/eregulations/db/port}
        ToPort: ${ssm:/eregulations/db/port}
        SourceSecurityGroupId: !Ref 'ServerlessSecurityGroup'

    DBSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: "RDS Subnet Group"
        SubnetIds:
          - subnet-01de8e5c081a2af6e
          - subnet-0c2e0a7a4fc60e6de
        Tags:
          - Key: "Name"
            Value: "DBSubnetGroup"
    # =============================================================================================
    # Aurora DB
    # =============================================================================================


    AuroraRDSClusterParameter15:
      Type: AWS::RDS::DBClusterParameterGroup
      Properties:
        Description: Parameter group for the Serverless Aurora RDS DB.
        Family: aurora-postgresql15
        Parameters:
          rds.force_ssl: 1

    AuroraRDSInstanceParameter15:
      Type: AWS::RDS::DBParameterGroup
      Properties:
        Description: Parameter group for the Serverless Aurora RDS DB.
        Family: aurora-postgresql15
        Parameters:
          shared_preload_libraries: auto_explain,pg_stat_statements,pg_hint_plan,pgaudit
          log_statement: "ddl"
          log_connections: 1
          log_disconnections: 1
          log_lock_waits: 1
          log_min_duration_statement: 5000
          auto_explain.log_min_duration: 5000
          auto_explain.log_verbose: 1
          log_rotation_age: 1440
          log_rotation_size: 102400
          rds.log_retention_period: 10080
          random_page_cost: 1
          track_activity_query_size: 16384
          idle_in_transaction_session_timeout: 7200000
          statement_timeout: 7200000
          search_path: '"$user",public'
          pgaudit.role: "rds_pgaudit"
          pgaudit.log: "ALL"

    RDSResource15:
      Type: AWS::RDS::DBCluster
      DeletionPolicy: Retain
      Properties:
        MasterUsername: ${self:custom.settings.USERNAME}
        StorageEncrypted: true
        MasterUserPassword: ${ssm:/eregulations/db/password}
        DBSubnetGroupName:
          Ref: DBSubnetGroup
        Engine: aurora-postgresql
        EngineVersion: "15.2"
        DatabaseName: 'eregs'
        BackupRetentionPeriod: 7
        DBClusterParameterGroupName:
          Ref: AuroraRDSClusterParameter15
        VpcSecurityGroupIds:
          - !Ref 'DBSecurityGroup'
    AuroraRDSInstance15:
      Type: AWS::RDS::DBInstance
      DeletionPolicy: Retain
      Properties:
        DBInstanceClass: db.r6g.large
        StorageEncrypted: true
        Engine: aurora-postgresql
        EngineVersion: "15.2"
        PubliclyAccessible: false
        DBParameterGroupName:
          Ref: AuroraRDSInstanceParameter15
        DBClusterIdentifier:
          Ref: RDSResource15

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-go-plugin
  - serverless-cloudfront-invalidate
  - serverless-associate-waf
